Add predicate methods (#89)
DmitryTsepelev/store_model pull request #97
Opened 2021-07-02 15:38 UTC by f-mer

This PR adds predicate methods as suggested in #89. 

It is loosely modeled after the [implementation in rails](https://github.com/rails/rails/blob/56d8ff83726bb6c0b1f570deb057835f90a75e30/activerecord/lib/active_record/attribute_methods/query.rb). 
I'm not 100% sure about the `method_missing` based implementation but at least that is how rails does it. Any thoughts?

2021-07-05 11:47 UTC, DmitryTsepelev requested changes
LGTM! I have one minor suggestion below

2021-07-05 11:47 UTC, DmitryTsepelev commented on lib/store_model/model.rb
> +      end
looks like we can reduce it to
```suggestion
      when 0 then false
      else value.present?
      end
```

2021-07-05 12:48 UTC, f-mer commented
Cool! Should I add a changelog entry and squash the commits?

2021-07-05 14:25 UTC, DmitryTsepelev commented
My suggestion was a bit different 🙂 `true.present?` is true, `false.present?` and `nil.present?` are false, so we only need to check zero. And yes, I'm ready to merge as soon as you done with the changelog.

2021-07-05 14:48 UTC, f-mer commented
Ouch, now I see. Thanks! :slightly_smiling_face:

2021-07-06 06:31 UTC, DmitryTsepelev approved these changes
So cool, thank you so much!

2021-07-06 06:34 UTC, merged